name: Label Pull Request
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  apply_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
          
            const creator = context.payload.sender.login
            console.log("CREATOR", creator)
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['enhancement']
            })
